name: appsyncmasterclass

schema: schema.api.graphql

authentication: 
  type: AMAZON_COGNITO_USER_POOLS
  config:
    awsRegion: us-east-1
    defaultAction: ALLOW
    userPoolId: !Ref CognitoUserPool

dataSources:
  usersTable:
    type: AMAZON_DYNAMODB
    description: "Users table"
    config:
      tableName: !Ref UsersTable

  tweetsTable:
    type: AMAZON_DYNAMODB
    description: "Tweets table"
    config:
      tableName: !Ref TweetsTable

  timelinesTable:
    type: AMAZON_DYNAMODB
    description: "Timelines table"
    config:
      tableName: !Ref TimelinesTable

  likesTable:
    type: AMAZON_DYNAMODB
    description: "Likes table"
    config:
      tableName: !Ref LikesTable

  likeMutation:
    type: AMAZON_DYNAMODB
    description: "Likes table"
    config:
      tableName: !Ref LikesTable
      iamRoleStatements:
        - Effect: Allow
          Action:
            - dynamodb:PutItem
          Resource: !GetAtt LikesTable.Arn
        - Effect: Allow
          Action:
            - dynamodb:UpdateItem
          Resource:
            - !GetAtt UsersTable.Arn
            - !GetAtt TweetsTable.Arn

  getImageUrlFunction:
    type: 'AWS_LAMBDA'
    config:
      functionName: getImageUploadUrl

  tweetFunction:
    type: 'AWS_LAMBDA'
    config:
      functionName: tweet

resolvers:
  # Queries
  Query.getMyProfile:
    functions:
      - dataSource: usersTable
        request: mapping-templates/Query.getMyProfile.request.vtl
        response: mapping-templates/Query.getMyProfile.response.vtl

  Query.getTweets:
    functions:
      - dataSource: tweetsTable
        request: mapping-templates/Query.getTweets.request.vtl
        response: mapping-templates/Query.getTweets.response.vtl

  Query.getImageUploadUrl:
    kind: UNIT
    dataSource: getImageUrlFunction

  Query.getMyTimeline:
    functions:
      - dataSource: timelinesTable
        request: mapping-templates/Query.getMyTimeline.request.vtl
        response: mapping-templates/Query.getMyTimeline.response.vtl

  # Nested fields
  profile:
    type: Tweet
    field: profile
    functions:
      - dataSource: usersTable
        request: mapping-templates/Tweet.profile.request.vtl
        response: mapping-templates/Tweet.profile.response.vtl

  tweets:
    type: TimelinePage
    field: tweets
    functions:
      - dataSource: tweetsTable
        request: mapping-templates/TimelinePage.tweets.request.vtl
        response: mapping-templates/TimelinePage.tweets.response.vtl

  # Mutations
  Mutation.editMyProfile:
    functions:
      - dataSource: usersTable
        request: mapping-templates/Mutation.editMyProfile.request.vtl
        response: mapping-templates/Mutation.editMyProfile.response.vtl

  Mutation.tweet:
      kind: UNIT
      dataSource: tweetFunction

  Mutation.like:
      kind: UNIT
      dataSource: likeMutation
      request: mapping-templates/Mutation.like.request.vtl
      response: mapping-templates/Mutation.like.response.vtl

substitutions:
  TweetsTable: !Ref TweetsTable
  LikesTable: !Ref LikesTable
  UsersTable: !Ref UsersTable